# Site wide configuration

title: Brian R. Gaines
locale: en_US
description:  Describe your website here.
logo: Gaines.jpg
search: false
url: #brgaines.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Brian R. Gaines
  avatar: Gaines.jpg
  email: brgaines@ncsu.edu
  disqus-shortname:
  twitter: brgainesStats
  facebook: #username
  github: brgaines
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: BrianGainesStats #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: 
    analytics: UA-58411279-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
